name: Bump Package Version

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Bump Version
      if: ${{ secrets.PUBLISHED == 'true' }}
      uses: google-github-actions/release-please-action@v3
      with:
        release-type: node
        package-name: <YOUR_PACKAGE_NAME_HERE>
        token: ${{ secrets.GITHUB_TOKEN }}
